# Generated by Django 3.2.4 on 2021-11-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'enroll',
                'managed': False,
            },
        ),
    ]
